---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaozhengwei.
--- DateTime: 2021/11/2 10:26
---

Account = {
    balance = 0;
}

function Account:New(o)
    o = o or {};
    self.__index = self;
    setmetatable(o, self);
    return o;
end

function Account:deposit(v)
    self.balance = self.balance + v;
end

function Account:withDraw(v)
    if v > self.balance then
        error("insufficient funds");
    end
    self.balance = self.balance - v;
end