--- Lua程序设计书本事例
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaozhengwei.
--- DateTime: 2021/11/10 15:35
---

--- Lua程序设计书本事例
local myBookTest = {};

--- 6 函数
myBookTest.C6 = {
    --- 可变长参数函数
    VarargExpFunc = function(...)
        local s = 0;
        for i, v in pairs{...} do
            s = s + v;
        end
        print("myBookTest.C6.VarargExpFunc = " .. s);
    end;

    SelectFunc = function(...)
        local s = 0;
        for i = 1, select("#", ...) do
            s = s + select(i, ...);
        end
        print("myBookTest.C6.SelectFunc = " .. s);
    end;
};

myBookTest.C10 = {
    -- string 方法
    StringFunc = function ()
        -- find
        local str1 = "UI_zzw zzw_UI";
        local i,j = string.find(str1, "zzw");
        print("myBookTest.C10.StringFunc  find = " .. i , j); -- 4,6

        -- match
        local str2 = "现在是 2021年11月16日16:35:05  !!!!!!";
        print("myBookTest.C10.StringFunc  match = " .. string.match(str2, "%d+年%d+月%d+日%d+:%d+:%d+")); -- 2021年11月16日16:35:05

        -- gsub
        local str3 = "local i； local v;";
        print("myBookTest.C10.StringFunc  gsub = " .. string.gsub(str3, "；", ";"));

        --sub
        local str4 = "UI_zzw";
        print("myBookTest.C10.StringFunc  sub = " .. string.sub(str4, 1,3));
    end;
};

_G.myBookTest = myBookTest;