---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaozhengwei.
--- DateTime: 2021/11/8 11:26
---

local self = {};

UIFormId = {
    MainUI = 1;
    RewardUI = 2;
}

function MyModuleTest2Func()
    self.PrintStr("This is MyModuleTest2Func");
end

function self.PrintStr(str)
    print(str);
end

-- 错误
--local function PrintStr(str)
--    print(str);
--end