---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaozhengwei.
--- DateTime: 2021/11/8 11:05

---@class ModuleTest01
local module01 = {};

module01.myNum = 12;

module01.AddNum_Static = function(num1, num2)
    PrintFunc_Local("ModuleTest01  AddNum_Static=" .. (num1 + num2));
end

function PrintFunc_Local(str)
    print(str);
end

function module01:AddNum_Public(num1, num2)
    PrintFunc_Local("ModuleTest01  AddNum_Public=" .. (num1 + num2));
end

return module01;    -- 必要