--- Player基类
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaozhengwei.
--- DateTime: 2021/11/1 18:15
---

---@class Player
---@field public name string @名字
local Player = {
    name = "",
};

Player.__index = Player;

function Player:create(name)
    local p = {};

    setmetatable(p, Player);

    p.name = name;

    return p;
end

function Player:Talk(str)
    print(self.name .. " Talk: " .. str);
end

_G.Player = Player;  --因为Player是local的，所以设定为全局表