--- Player基类
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaozhengwei.
--- DateTime: 2021/11/1 18:15
---

local Person = {};
function Person:create(name)
    local p = {};

    self.__index = self;
    setmetatable(p, Person);

    p.name = name;
    return p;
end

function Person:Talk(str)
    print(self.name .. " : " .. str);
end

_G.Person = Person;  --设定为全局表