---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhaozhengwei.
--- DateTime: 2021/12/14 11:04
---

---@class SubPlayer Player的子类
---@field public age number
local SubPlayer = {
    age = 0,
}

SubPlayer.__index = SubPlayer;

setmetatable(SubPlayer, Player);

function SubPlayer:create(name, age)
    local t = {};
    t = Player:create(name);

    setmetatable(t, SubPlayer);

    t.age = age;

    return t;
end


--- 子类重写父类Talk方法
---@param str string 描述
function SubPlayer:Talk(str)
    print(self.name .. " won't Talk: " .. str);
end


--- 子类方法ReName
---@param str string 名字
---@public
function SubPlayer:ReName(str)
    self.name = str;
end


--- ReAge
---@param age number
---@private
function SubPlayer:ReAge(age)
    self.age = age;
end

_G.SubPlayer = SubPlayer;
